#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use GreenCape\CodeGen\Command\GenerateCommand;
use Symfony\Component\Console\Application;

$application = new Application();

$application->add(new GenerateCommand());

$application->run();
