<?template scope="application"?>
swagger: '2.0'
info:
  title: {{ project.title }}
  description: {{ project.description }}
  version: "{{ project.version }}"
schemes:
  - https
basePath: /v1
produces:
  - application/json
paths:
{% for entity in project.entities %}
  /{{ entity.name | plural | dash }}:
    get:
      operationId: "get{{ entity.name | plural | class }}"
      summary: List {{ entity.name | plural | title }}
      description: |
        The {{ entity.name | plural | title }} endpoint returns information about the {{ entity.name | plural | title | lower }}.
        The response includes the display name and other details about each {{ entity.name | singular | title | lower }},
        and lists the {{ entity.name | plural | title | lower }} in the proper display order.
      tags:
        - {{ entity.name | plural | title }}
      responses:
        200:
          description: An array of {{ entity.name | plural | title | lower }}
          schema:
            type: array
            items:
              $ref: '#/definitions/{{ entity.name | singular | class }}'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
    post:
      operationId: "create{{ entity.name | singular | class }}"
      summary: Create {{ entity.name | singular | title }}
      description: |
      tags:
        - {{ entity.name | plural | title }}
      responses:
        200:
          description: The {{ entity.name | singular | title | lower }} with the newly created ID.
          schema:
            $ref: '#/definitions/{{ entity.name | singular | class }}'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /{{ entity.name | plural | dash }}/{id}:
    get:
      operationId: "get{{ entity.name | singular | class }}"
      summary: Get the {{ entity.name | singular | title }} with the given ID.
      description: |
      tags:
        - {{ entity.name | plural | title }}
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          format: int32
      responses:
        '200':
          description:  The {{ entity.name | singular | title | lower }}
          schema:
            $ref: '#/definitions/{{ entity.name | singular | class }}'
{% endfor %}
definitions:
{% for entity in project.entities %}
  {{ entity.name | singular | class }}:
    type: object
    properties:
{% for property in entity.properties %}
      {{ property.name }}:
        type: {{ property.type }}
{% if property.type == 'integer' %}
        format: int32
{% endif %}
{% if property.description %}
        description: {{ property.description }}
{% endif %}
{% endfor %}
{% endfor %}
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
